addons:
  sonarcloud:
    organization: "pluralism"
    token:
      secure: "$SONAR_TOKEN"
dist: trusty
language: java
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - bash <(curl -s https://codecov.io/bash)